export default async ({page}) => {
  const WS='W4QBF1XTURESO01';
  const out={};
  await page.goto(`https://airion-cargo.store/w/${WS}/calls`, {waitUntil:'domcontentloaded'});
  await page.waitForTimeout(3500);
  await page.evaluate(()=>{ const b=[...document.querySelectorAll('button')].filter(x=>x.getBoundingClientRect().width>0).find(x=>(x.innerText||'').trim()==='Start now'); if(b) b.click(); });
  await page.waitForTimeout(2500);
  const nm = await page.$('[role=dialog] input[type=text]'); if (nm) await nm.fill('QA limit test');
  await page.evaluate(()=>{ const pick=v=>{const r=[...document.querySelectorAll('[role=dialog] input[type=radio]')].find(x=>x.value===v); if(r) r.click();}; pick('public'); pick('open'); });
  await page.waitForTimeout(500);
  await page.evaluate(()=>{ const b=[...document.querySelectorAll('[role=dialog] button')].find(x=>(x.innerText||'').trim()==='Start call'); if(b) b.click(); });
  await page.waitForTimeout(7000);
  out.meetingId = (page.url().match(/\/call\/([A-Za-z0-9]+)/)||[])[1]||null;
  await page.evaluate(()=>{ const b=[...document.querySelectorAll('button')].find(x=>x.getAttribute('aria-label')==='Meeting settings'); if(b) b.click(); });
  await page.waitForTimeout(2500);
  const num = await page.$('[role=dialog] input[type=number]');
  out.attrs = await page.evaluate(()=>{ const i=document.querySelector('[role=dialog] input[type=number]'); return i? {min:i.getAttribute('min'), max:i.getAttribute('max'), step:i.getAttribute('step'), val:i.value}:null; });
  const trial = async (v) => {
    await num.fill(String(v)); await page.waitForTimeout(500);
    const accepted = await page.evaluate(()=>{ const i=document.querySelector('[role=dialog] input[type=number]'); return {v:i.value, valid:i.checkValidity? i.checkValidity():null, msg:i.validationMessage||''}; });
    await page.evaluate(()=>{ const b=[...document.querySelectorAll('[role=dialog] button')].find(x=>(x.innerText||'').trim()==='Save'); if(b) b.click(); });
    await page.waitForTimeout(3500);
    const api = await page.evaluate(async()=>{ const j=await (await fetch('/api/v1/meetings/current',{credentials:'include'})).json().catch(()=>null); const m=j&&j.meeting; return m? m.max_participants : null; });
    const err = await page.evaluate(()=>{ const t=document.body.innerText.replace(/\s+/g,' '); return (t.match(/.{0,40}(must be|invalid|error|Try again|at least).{0,50}/i)||[])[0]||null; });
    return {typed:v, accepted, apiMax:api, err};
  };
  out.negative = await trial(-5);
  out.huge = await trial(999999);
  return out;
};
