export default async ({page}) => {
  const out={}; const net=[];
  page.on('response', async r=>{ if(/\/meeting\//.test(r.url()) && r.request().method()!=='GET'){ net.push({s:r.status(), req:(r.request().postData()||'').slice(0,90)}); }});
  await page.keyboard.press('Escape'); await page.waitForTimeout(600);
  await page.evaluate(()=>{const b=[...document.querySelectorAll('button[aria-label="Meeting settings"]')].find(x=>x.getClientRects().length); if(b)b.click();});
  await page.waitForTimeout(2500);
  const inp = await page.$('[role="dialog"] input[type="text"]');
  if (!inp) return {err:'no name input'};
  await inp.click();
  await page.keyboard.down('Meta'); await page.keyboard.press('a'); await page.keyboard.up('Meta');
  await page.keyboard.type('RENAMED-SR', {delay:20});
  await page.waitForTimeout(800);
  out.saved = await page.evaluate(()=>{const ds=[...document.querySelectorAll('[role="dialog"]')].filter(e=>e.getClientRects().length); const d=ds[ds.length-1];
    const b=[...d.querySelectorAll('button')].find(x=>/^save$/i.test((x.textContent||'').trim())); if(!b||b.disabled) return {ok:false,dis:b?b.disabled:null}; b.click(); return {ok:true};});
  await page.waitForTimeout(3500);
  await page.keyboard.press('Escape'); await page.waitForTimeout(800);
  out.hostHeader = await page.evaluate(()=>{const h=document.querySelector('header'); return (h?h.innerText:(document.body.innerText||'')).replace(/\n+/g,' | ').slice(0,90);});
  out.net=net;
  return out;
};
