export default async ({page}) => {
  const steps=[];
  const netlog=[];
  page.on('response', async r=>{const u=r.url(); if(u.includes('/api/v1/')&&r.request().method()!=='GET'){let b='';try{b=(await r.text()).slice(0,150);}catch(e){} netlog.push(`${r.request().method()} ${r.status()} ${u.replace('https://airion-cargo.store','')} :: ${b}`);}});
  const st = async ()=> await page.evaluate(async()=>{const c=await (await fetch('/api/v1/meetings/current',{credentials:'include'})).json();
    return {overlay: !!document.querySelector('[data-testid="call-overlay-expanded"]'), cur: c&&c.meeting?c.meeting.id:null};});
  steps.push(['before', await st()]);
  const b = await page.$('[data-testid="call-controls-leave"]');
  if (!b) return {err:'no leave', steps};
  const info = await page.evaluate(()=>{const e=document.querySelector('[data-testid="call-controls-leave"]');const r=e.getBoundingClientRect();
    const top=document.elementFromPoint(r.x+r.width/2, r.y+r.height/2);
    return {rect:r.toJSON(), disabled:e.disabled, topEl: top? (top.tagName+'|'+(top.getAttribute('data-testid')||top.className.slice(0,40))) : null};});
  steps.push(['btn', info]);
  await b.click({force:true});
  await page.waitForTimeout(3000);
  steps.push(['after click', await st()]);
  const dlgs = await page.evaluate(()=>[...document.querySelectorAll('[role="dialog"],[role="alertdialog"]')].filter(d=>d.getAttribute('data-testid')!=='call-overlay-expanded').map(d=>({tid:d.getAttribute('data-testid'), t:d.innerText.replace(/\n+/g,' | ').slice(0,220)})));
  steps.push(['dialogs', dlgs]);
  await page.waitForTimeout(4000);
  steps.push(['after 7s', await st()]);
  return {steps, net: netlog};
};
